repos:
  - repo: local
    hooks:
      - id: auto-format
        name: Auto-format with black (auto-fix)
        entry: python scripts/pre_commit_auto_format.py
        language: system
        files: ^(clustrix/|tests/).*\.py$
        pass_filenames: false
        
  - repo: https://github.com/psf/black
    rev: 25.1.0  # Use same version as local environment
    hooks:
      - id: black
        name: Black formatting verification
        language_version: python3
        files: ^(clustrix/|tests/)
        
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        # Use the configuration from .flake8 file instead of inline args
        files: ^(clustrix/|tests/)
        
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        # Only check clustrix/ package, not tests (consistent with pyproject.toml)
        files: ^clustrix/
        args: ["--ignore-missing-imports"]
        additional_dependencies: [types-PyYAML, types-requests, types-paramiko]