repos:
  - repo: local
    hooks:
      - id: auto-format
        name: Auto-format with black (auto-fix)
        entry: python scripts/pre_commit_auto_format.py
        language: system
        files: ^(clustrix/|tests/unit/|tests/integration/|examples/|scripts/).*\.py$
        pass_filenames: false
        
  - repo: https://github.com/psf/black
    rev: 25.1.0  # Use same version as local environment
    hooks:
      - id: black
        name: Black formatting verification
        language_version: python3
        files: ^(clustrix/|tests/unit/|tests/integration/|examples/|scripts/)
        
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [
          "--max-line-length=88",
          "--extend-ignore=E203,W503,F401,E722,F541,F841,F811,E731,E501,W291,W293,F824,E402",
          "--exclude=tests/real_world/,tests/comprehensive/,debug_*.py,user_*.py,cleanup_*.py,destroy_*.py"
        ]
        files: ^(clustrix/|tests/unit/|tests/integration/|examples/|scripts/)
        
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--exclude", "tests/real_world/|tests/comprehensive/|debug_|user_|cleanup_|destroy_"]
        files: ^(clustrix/|tests/unit/|tests/integration/|examples/|scripts/).*\.py$
        additional_dependencies: [types-PyYAML, types-requests, types-paramiko]