# Clustrix configuration for ndoli.dartmouth.edu SLURM cluster
cluster_type: "slurm"
cluster_host: "ndoli.dartmouth.edu"
username: "f002d6b"
remote_work_dir: "/dartfs-hpc/rc/home/b/f002d6b/clustrix"
python_executable: "python3"

# SLURM defaults
default_cores: 2
default_memory: "4GB"
default_time: "00:10:00"
default_partition: "standard"

# Cluster-specific environment setup
module_loads:
  - "python"

environment_variables:
  OMP_NUM_THREADS: "1"

# Commands to run before creating virtual environment
pre_execution_commands:
  - "export PATH=/usr/bin:$PATH"
  - "which python3 || echo 'Python3 not found in PATH'"
  - "module list"