active_profile: Local single-core
profiles:
  Local single-core:
    aks_cluster_name: null
    api_key: null
    async_submit: false
    auto_parallel: true
    aws_access_key: null
    aws_access_key_id: null
    aws_cluster_type: null
    aws_instance_type: null
    aws_profile: null
    aws_region: null
    aws_secret_access_key: null
    aws_secret_key: null
    azure_client_id: null
    azure_client_secret: null
    azure_instance_type: null
    azure_region: null
    azure_resource_group: null
    azure_subscription_id: null
    azure_tenant_id: null
    cache_credentials: true
    cleanup_on_success: true
    cloud_auto_configure: false
    cloud_provider: manual
    cloud_region: null
    cluster_host: null
    cluster_port: 22
    cluster_type: local
    conda_env_name: null
    cost_monitoring: false
    credential_cache_ttl: 300
    default_cores: 1
    default_memory: 16.25GB
    default_partition: null
    default_queue: null
    default_time: 01:00:00
    eks_cluster_name: null
    environment_variables: {}
    gcp_instance_type: null
    gcp_project_id: null
    gcp_region: null
    gcp_service_account_key: null
    gcp_zone: null
    gke_cluster_name: null
    hf_hardware: null
    hf_sdk: null
    hf_token: null
    hf_username: null
    job_poll_interval: 30
    k8s_backoff_limit: 3
    k8s_image: python:3.11-slim
    k8s_job_ttl_seconds: 3600
    k8s_namespace: default
    k8s_pull_policy: IfNotPresent
    k8s_remote: false
    k8s_service_account: null
    key_file: null
    lambda_api_key: null
    lambda_instance_type: null
    local_cache_dir: ~/.clustrix/cache
    local_parallel_threshold: 1000
    local_work_dir: null
    max_parallel_jobs: 100
    module_loads: []
    onepassword_note: ''
    package_manager: auto
    password: null
    password_env_var: ''
    pre_execution_commands: []
    prefer_local_parallel: false
    python_executable: python
    remote_work_dir: /tmp/clustrix
    ssh_port: 22
    use_1password: false
    use_env_password: false
    username: null
