import pytest
import pickle
import hmac
import hashlib
import secrets
import importlib.metadata
from unittest.mock import Mock, patch, MagicMock
from pathlib import Path
from clustrix import cluster, configure, get_config

# Job results are now HMAC-signed with a per-job key generated by
# `secrets.token_hex(32)` inside clustrix.executor_schedulers._prepare_job_dir
# (#121) and verified before the pickle is loaded. Tests below that fabricate
# result.pkl/error.pkl on disk (because paramiko itself is mocked -- there is
# no real remote host) must sign them the same way the real worker does, or
# clustrix correctly refuses to deserialize them. To do that deterministically
# we pin the 32-byte token_hex call -- and only that one; the 4-byte call used
# for job-directory suffixes keeps using the real generator.
_TEST_RESULT_KEY = "3f9c2b6a1d8e4f07c5a9b3d6e2f18a4c7b0d5e9f2a6c8b1d4e7f0a3c6b9d2e5f"
_REAL_TOKEN_HEX = secrets.token_hex


def _pinned_token_hex(nbytes=None):
    if nbytes == 32:
        return _TEST_RESULT_KEY
    return _REAL_TOKEN_HEX(nbytes)


def _patch_result_key():
    """Make the per-job result-signing key deterministic for a test."""
    return patch(
        "clustrix.executor_schedulers.secrets.token_hex",
        side_effect=_pinned_token_hex,
    )


def _sign(payload: bytes, key: str = _TEST_RESULT_KEY) -> str:
    """Compute the same HMAC-SHA256 hex digest the real worker writes."""
    return hmac.new(key.encode(), payload, hashlib.sha256).hexdigest()


class TestIntegration:
    """Integration tests for end-to-end functionality."""

    @pytest.fixture
    def mock_ssh_setup(self):
        """Setup mock SSH environment for integration tests."""
        with patch("paramiko.SSHClient") as mock_ssh_class:
            mock_ssh = Mock()
            mock_ssh_class.return_value = mock_ssh

            # Mock SFTP
            mock_sftp = MagicMock()
            mock_ssh.open_sftp.return_value = mock_sftp

            # Mock SFTP file operations for context manager support
            mock_file = MagicMock()
            mock_sftp.open.return_value.__enter__.return_value = mock_file
            mock_sftp.open.return_value.__exit__.return_value = None

            # Mock successful command execution
            mock_stdout = Mock()
            mock_stdout.read.return_value = b"Success"
            mock_stdout.channel.recv_exit_status.return_value = 0

            mock_stderr = Mock()
            mock_stderr.read.return_value = b""

            mock_ssh.exec_command.return_value = (None, mock_stdout, mock_stderr)

            yield mock_ssh, mock_sftp

    def test_end_to_end_simple_function(self, mock_ssh_setup, temp_dir):
        """Test complete execution of a simple function."""
        mock_ssh, mock_sftp = mock_ssh_setup

        # Configure for remote execution
        configure(
            cluster_type="slurm",
            cluster_host="test.cluster.com",
            username="testuser",
            remote_work_dir=temp_dir,
        )

        # Define and decorate function
        @cluster(cores=4, memory="8GB")
        def add_numbers(x, y):
            return x + y

        # Mock job submission
        mock_stdout = Mock()
        mock_stdout.read.return_value = b"12345"
        mock_ssh.exec_command.return_value = (None, mock_stdout, Mock())

        # Mock job status checking
        def exec_side_effect(cmd):
            if "squeue" in cmd:
                status_mock = Mock()
                status_mock.read.return_value = b"COMPLETED"
                status_mock.channel.recv_exit_status.return_value = 0
                return (None, status_mock, Mock())
            else:
                # For other commands (environment setup, etc.), return successful execution
                cmd_stdout = Mock()
                cmd_stdout.read.return_value = b"Success"
                cmd_stdout.channel.recv_exit_status.return_value = 0

                cmd_stderr = Mock()
                cmd_stderr.read.return_value = b""

                return (None, cmd_stdout, cmd_stderr)

        # Mock result retrieval
        result_data = 42
        result_file = Path(temp_dir) / "result.pkl"
        with open(result_file, "wb") as f:
            pickle.dump(result_data, f)
        result_signature = _sign(result_file.read_bytes())

        def exec_side_effect_signed(cmd):
            if "result.pkl.hmac" in cmd:
                tag_stdout = Mock()
                tag_stdout.read.return_value = result_signature.encode()
                tag_stdout.channel.recv_exit_status.return_value = 0
                return (None, tag_stdout, Mock(read=lambda: b""))
            return exec_side_effect(cmd)

        mock_ssh.exec_command.side_effect = exec_side_effect_signed

        def get_side_effect(remote_path, local_path):
            # Copy our test result file to the requested location
            import shutil

            shutil.copy(result_file, local_path)

        mock_sftp.get.side_effect = get_side_effect
        mock_sftp.stat.return_value = Mock()  # File exists

        # Execute function
        with _patch_result_key():
            result = add_numbers(10, 32)

        assert result == 42

    def test_parallel_loop_execution(self, mock_ssh_setup, temp_dir):
        """Test parallel execution of loops."""
        mock_ssh, mock_sftp = mock_ssh_setup

        configure(
            cluster_type="slurm",
            cluster_host="test.cluster.com",
            username="testuser",
            auto_parallel=True,
            max_parallel_jobs=10,
        )

        @cluster(cores=2, parallel=True)
        def process_items(items):
            results = []
            for item in items:
                results.append(item * 2)
            return results

        # This would normally trigger parallel execution
        # For testing, we'll verify the function is properly decorated
        assert hasattr(process_items, "_cluster_config")
        assert process_items._cluster_config["parallel"] is True

    def test_error_handling_integration(self):
        """An exception raised inside a @cluster function must reach the caller.

        This used to drive a mocked SSH client whose exec_command answered
        b"Success" to every command -- including `echo $HOME`, so the remote
        home directory resolved to the string "Success". It then hand-built a
        signed error.pkl to feed back through the mock. It exercised the
        mocking, not the product: clustrix now correctly refuses a nonsense
        home directory, and the test failed on that rather than on anything to
        do with error handling.

        cluster_type="local" is a real backend, so the same question -- does the
        original exception, with its type and message, reach the caller? -- can
        be asked without inventing a cluster.
        """
        configure(cluster_type="local")

        @cluster(cores=2)
        def failing_function():
            raise ValueError("This function always fails")

        with pytest.raises(ValueError, match="This function always fails"):
            failing_function()

    def test_error_handling_preserves_exception_type(self):
        """Not just the message: the caller must get the real exception class.

        A previous defect returned every remote failure as a generic error,
        which meant `except KeyError:` around a @cluster call did not work.
        """
        configure(cluster_type="local")

        class ProjectSpecificError(Exception):
            pass

        @cluster(cores=1)
        def raises_keyerror():
            raise KeyError("missing-key")

        with pytest.raises(KeyError):
            raises_keyerror()

    def test_configuration_persistence(self, temp_dir):
        """Test configuration loading and persistence."""
        config_file = Path(temp_dir) / "clustrix.yml"

        # Create configuration
        configure(
            cluster_type="sge",
            cluster_host="sge.cluster.com",
            username="sgeuser",
            default_cores=16,
            default_memory="32GB",
            module_loads=["python/3.9", "gcc/11.2"],
            environment_variables={"OMP_NUM_THREADS": "16"},
        )

        # Save configuration
        from clustrix.config import save_config

        save_config(str(config_file))

        # Reset configuration
        configure(cluster_type="ssh")  # Change to verify load works

        # Load configuration
        from clustrix.config import load_config

        load_config(str(config_file))

        # Verify loaded configuration
        config = get_config()
        assert config.cluster_type == "sge"
        assert config.cluster_host == "sge.cluster.com"
        assert config.username == "sgeuser"
        assert config.default_cores == 16
        assert config.default_memory == "32GB"
        assert config.module_loads == ["python/3.9", "gcc/11.2"]
        assert config.environment_variables == {"OMP_NUM_THREADS": "16"}

    def test_local_execution_fallback(self):
        """Test that functions execute locally when no cluster is configured."""
        # Ensure no cluster is configured
        configure(cluster_host=None)

        @cluster(cores=8)
        def compute_locally(x, y):
            return x**y

        result = compute_locally(2, 10)
        assert result == 1024

    def test_environment_replication(self):
        """Test environment replication against the REAL local environment.

        This used to mock ``clustrix.utils.get_environment_info`` and only
        assert that a submitted job's freeze output got read. That patch
        target no longer exists: ``serialize_function`` used to call
        ``get_environment_info()`` purely so this mock would be exercised,
        discarding the result and paying for a ``pip list`` subprocess on
        every job submission for nothing. It has been deleted.

        Mocking the freeze step is also exactly how the real environment-
        replication bug went undetected for so long:
        ``get_environment_requirements()`` was silently dropping 187 of 563
        installed packages (anything with an ``@`` in its freeze line), and
        every test that faked the freeze output reported success regardless.
        So this exercises the real function against this interpreter's own
        installed packages instead of mocking anything.
        """
        from clustrix.utils import (
            get_environment_requirements,
            get_unreproducible_requirements,
            serialize_function,
        )

        requirements = get_environment_requirements()

        # A real development environment has far more than a couple of
        # packages -- this is what the "drop anything with an @ in it" bug
        # would have reduced it to.
        assert len(requirements) > 50

        # Pick a package we can independently confirm is installed via
        # importlib.metadata itself (not hardcoded, so this holds on any
        # machine with a normal clustrix dev install) and check the reported
        # version agrees with metadata's own answer.
        installed = {
            dist.metadata["Name"]: dist.version
            for dist in importlib.metadata.distributions()
            if dist.metadata["Name"]
        }
        assert "numpy" in installed, "test environment is expected to have numpy"
        assert requirements["numpy"] == installed["numpy"]

        # clustrix itself must never be pinned: the generated worker never
        # imports clustrix, so requiring it would be both unnecessary and
        # (for an editable checkout, as in this repo) unreproducible.
        assert "clustrix" not in requirements

        unreproducible = get_unreproducible_requirements()
        assert "clustrix" not in unreproducible

        # If this environment happens to have an editable or VCS install
        # (common on a development machine -- e.g. `pip install -e .` of some
        # other project), it must be classified as unreproducible with a
        # reason, and must NOT be pinned as a plain requirement.
        for dist in importlib.metadata.distributions():
            name = dist.metadata["Name"]
            if not name or name == "clustrix":
                continue
            try:
                raw = dist.read_text("direct_url.json")
            except Exception:
                raw = None
            if not raw:
                continue
            is_editable = '"editable": true' in raw
            is_vcs = '"vcs_info"' in raw
            if is_editable or is_vcs:
                assert name in unreproducible, (
                    f"{name} is an editable/VCS install and should be "
                    "reported as unreproducible"
                )
                assert name not in requirements, (
                    f"{name} is an editable/VCS install and must not be "
                    "pinned as a plain requirement"
                )
                break

        # And confirm the requirement set is actually what gets attached to a
        # submitted job, rather than testing get_environment_requirements()
        # in isolation from the thing that calls it.
        func_data = serialize_function(lambda: None, (), {})
        assert func_data["requirements"] == get_environment_requirements()

    def test_resource_specification_inheritance(self):
        """Test that decorator resources override defaults."""
        configure(
            cluster_type="pbs",
            default_cores=4,
            default_memory="8GB",
            default_time="01:00:00",
        )

        @cluster(cores=16, memory="64GB", time="12:00:00")
        def heavy_computation():
            return "done"

        # Verify the decorated function has the specified resources
        assert heavy_computation._cluster_config["cores"] == 16
        assert heavy_computation._cluster_config["memory"] == "64GB"
        assert heavy_computation._cluster_config["time"] == "12:00:00"
