"""SSH key automation, exercised against a real SSH server.

Every test in this module used to patch ``paramiko.SSHClient`` or the
``clustrix.ssh_utils`` function it was meant to be testing. The worst of them
is named in issue #117: ``test_validate_ssh_key_success`` mocked the SSH
client, called ``validate_ssh_key(...)``, and asserted the result was ``True``
-- with no key, no host, and no authentication anywhere in the picture.

What runs here instead is real: real keys generated by ``ssh-keygen`` onto a
real disk with real permissions, a real ``$HOME`` so nothing lands in the
developer's own ``~/.ssh``, and a real SSH server (``tests/ssh_server.py``) on
a loopback socket that really verifies possession of a key before it lets
anyone in.
"""

import os
import socket
import stat
from pathlib import Path

import paramiko
import pytest

from clustrix.ssh_utils import (
    setup_ssh_keys,
    detect_working_ssh_key,
    validate_ssh_key,
    generate_ssh_key_pair,
    deploy_ssh_key,
    find_ssh_keys,
)
from clustrix.config import ClusterConfig
from tests.ssh_server import LocalSSHServer, generate_keypair

#: A real password for a real server that exists for one test.
SSH_PASSWORD = "clustrix-test-password"


@pytest.fixture
def isolated_home(tmp_path):
    """A real ``$HOME`` for the duration of one test.

    Nothing is patched: the environment variable really changes, so
    ``Path.home()``, ``ssh-keygen``, ``known_hosts`` and ``~/.ssh/config`` all
    follow it exactly as they would for a different user. This is what keeps
    tests that really generate and really deploy keys out of the developer's
    own ``~/.ssh``.
    """
    home = tmp_path / "home"
    (home / ".ssh").mkdir(parents=True)
    os.chmod(home / ".ssh", 0o700)
    previous = os.environ.get("HOME")
    os.environ["HOME"] = str(home)
    try:
        yield home
    finally:
        if previous is None:
            del os.environ["HOME"]
        else:
            os.environ["HOME"] = previous


@pytest.fixture
def ssh_server(tmp_path):
    """A real SSH server on a loopback port, with its own home directory."""
    root = tmp_path / "remote"
    root.mkdir()
    with LocalSSHServer(root=root, password=SSH_PASSWORD) as server:
        server.root_path = root
        yield server


def _config(server, **overrides):
    kwargs = dict(
        cluster_host=server.host,
        cluster_port=server.port,
        username="testuser",
        # The server's host key is generated per run and cannot be in any
        # known_hosts file; host key verification has its own tests in
        # tests/unit/test_host_key_policy.py.
        ssh_host_key_policy="auto_add",
    )
    kwargs.update(overrides)
    return ClusterConfig(**kwargs)


def _authorize(server, public_key_path):
    """Put a real public key in the server account's real authorized_keys."""
    ssh_dir = server.root_path / ".ssh"
    ssh_dir.mkdir(mode=0o700, exist_ok=True)
    authorized = ssh_dir / "authorized_keys"
    with open(authorized, "a") as handle:
        handle.write(Path(public_key_path).read_text())
    os.chmod(authorized, 0o600)


class TestSSHKeyAutomation:
    """Test SSH key automation functionality."""

    def test_setup_ssh_keys_missing_config(self):
        """Test setup_ssh_keys with missing config parameters."""
        config = ClusterConfig()

        result = setup_ssh_keys(config, password="test")

        assert not result["success"]
        assert "cluster_host must be specified" in result["error"]

    def test_setup_ssh_keys_missing_username(self):
        """Test setup_ssh_keys with missing username."""
        config = ClusterConfig(cluster_host="test.example.com")

        result = setup_ssh_keys(config, password="test")

        assert not result["success"]
        assert "username must be specified" in result["error"]

    def test_setup_ssh_keys_existing_key(self, isolated_home, ssh_server):
        """A key that already works is found, and nothing is deployed.

        The old version patched ``detect_existing_ssh_key`` to return a path
        that did not exist and asserted that path came back. Here the key is
        real, it is really in the server's ``authorized_keys``, and the reason
        it is "found" is that clustrix really authenticated with it.
        """
        private_key = generate_keypair(isolated_home / ".ssh", "id_ed25519")
        _authorize(ssh_server, f"{private_key}.pub")

        config = _config(ssh_server)
        result = setup_ssh_keys(config, password=SSH_PASSWORD)

        assert result["success"]
        assert result["key_already_existed"]
        assert result["key_path"] == str(private_key)
        assert not result["key_deployed"]
        assert result["connection_tested"]
        # The far end really authenticated a public key, not a password.
        assert ("testuser", "publickey") in ssh_server.authentications
        # Nothing was written to the server's authorized_keys by clustrix.
        assert ssh_server.commands == []

    def test_setup_ssh_keys_new_key_generation(self, isolated_home, ssh_server):
        """Generate a real key, deploy it over real SSH, and log in with it.

        The old version patched ``generate_ssh_key``, ``deploy_public_key``,
        ``update_ssh_config`` and ``Path.exists`` and then asserted that the
        stubs it had installed were called. Nothing was generated and nothing
        was deployed.

        ``connection_tested`` used to be asserted **False** here, pinning a
        real defect: step 5 of ``setup_ssh_keys`` tests the connection with
        ``detect_existing_ssh_key``, which asked ``find_ssh_keys()`` for
        candidates, and ``find_ssh_keys()`` only ever tried six exact
        filenames. The key clustrix had just generated is named
        ``id_ed25519_clustrix_<user>_<alias>``, which was not one of them, so
        the check could never succeed for a key clustrix generated itself.

        Issue #154 fixed the discovery, so the assertion is now the opposite
        one -- and it is the strong form: the key that step 5 found has to be
        the very key this call generated, proving the verification really
        exercised it rather than stumbling onto some other working key.
        """
        config = _config(ssh_server)

        result = setup_ssh_keys(
            config, password=SSH_PASSWORD, cluster_alias="test_alias"
        )

        assert result["success"], result["error"]
        assert not result["key_already_existed"]
        assert result["key_deployed"]
        assert result["details"]["key_generated"] is True

        # The naming convention, asserted against a key that exists.
        key_path = Path(result["key_path"])
        assert key_path.name == "id_ed25519_clustrix_testuser_test_alias"
        assert key_path.exists() and Path(f"{key_path}.pub").exists()
        assert key_path.parent == isolated_home / ".ssh"

        # It really reached the server's authorized_keys...
        authorized = (ssh_server.root_path / ".ssh" / "authorized_keys").read_text()
        assert Path(f"{key_path}.pub").read_text().split()[1] in authorized

        # ...and it really works: this is a fresh, real authentication.
        assert validate_ssh_key(
            ssh_server.host,
            "testuser",
            str(key_path),
            ssh_server.port,
            config=config,
        )

        # The SSH config entry was really written to the real file.
        ssh_config = (isolated_home / ".ssh" / "config").read_text()
        assert "Host test_alias" in ssh_config
        assert f"Port {ssh_server.port}" in ssh_config
        assert result["details"]["ssh_config_updated"] is True

        # Step 5 really verified the key it had just deployed.
        assert result["connection_tested"] is True
        assert "connection_test_warning" not in result["details"]
        # ...and that is only meaningful because discovery can see the key:
        assert str(key_path) in find_ssh_keys()

    def test_setup_ssh_keys_without_alias_names_the_key_after_the_host(
        self, isolated_home, ssh_server
    ):
        """The no-alias naming convention, on a key that really exists.

        Replaces a test that patched four functions and asserted a substring
        of a path that was never created.
        """
        config = _config(ssh_server)

        result = setup_ssh_keys(config, password=SSH_PASSWORD, key_type="ed25519")

        assert result["success"], result["error"]
        clean_host = ssh_server.host.replace(".", "_")
        key_path = Path(result["key_path"])
        assert key_path.name == f"id_ed25519_clustrix_testuser_{clean_host}"
        assert key_path.exists()
        assert validate_ssh_key(
            ssh_server.host, "testuser", str(key_path), ssh_server.port, config=config
        )

    def test_setup_ssh_keys_force_refresh(self, isolated_home, ssh_server):
        """Force refresh really replaces the key material on disk.

        The old version patched ``Path.exists``, ``Path.unlink``,
        ``generate_ssh_key`` and ``deploy_public_key``, then asserted the
        stubs had been called. It could not tell a replaced key from an
        untouched one. This compares the bytes.
        """
        config = _config(ssh_server)

        first = setup_ssh_keys(config, password=SSH_PASSWORD, cluster_alias="refresh")
        assert first["success"], first["error"]
        original_public_key = Path(f"{first['key_path']}.pub").read_text()

        second = setup_ssh_keys(
            config,
            password=SSH_PASSWORD,
            cluster_alias="refresh",
            force_refresh=True,
        )

        assert second["success"], second["error"]
        assert second["key_path"] == first["key_path"]
        assert not second["key_already_existed"]
        # Same path, genuinely different key.
        refreshed_public_key = Path(f"{second['key_path']}.pub").read_text()
        assert refreshed_public_key != original_public_key
        # And the new key is the one that now opens the door.
        assert validate_ssh_key(
            ssh_server.host,
            "testuser",
            second["key_path"],
            ssh_server.port,
            config=config,
        )

    def test_validate_ssh_key_success(self, isolated_home, ssh_server):
        """Named in issue #117: this used to validate no key at all.

        The old version patched ``paramiko.SSHClient``, called
        ``validate_ssh_key`` with the literal path ``"/path/to/key"``, and
        asserted ``True`` -- then asserted the Mock had been called with the
        arguments the function passes it. It would have passed against a
        ``validate_ssh_key`` that did nothing but ``return True``.

        Here the key is generated by ``ssh-keygen``, it is on disk with the
        permissions ``ssh-keygen`` gives it, the server holds only its public
        half, and ``True`` is returned because a real SSH server really
        completed public-key authentication.
        """
        private_key = generate_keypair(isolated_home / ".ssh", "id_ed25519")
        public_key = Path(f"{private_key}.pub")

        # Real artifacts, in the real formats clustrix has to read.
        assert private_key.read_text().startswith("-----BEGIN OPENSSH PRIVATE KEY-----")
        assert public_key.read_text().startswith("ssh-ed25519 ")
        assert stat.S_IMODE(private_key.stat().st_mode) == 0o600

        _authorize(ssh_server, public_key)

        assert (
            validate_ssh_key(
                ssh_server.host,
                "testuser",
                str(private_key),
                ssh_server.port,
                config=_config(ssh_server),
            )
            is True
        )
        assert ("testuser", "publickey") in ssh_server.authentications

    def test_validate_ssh_key_failure(self, isolated_home, ssh_server):
        """A key the server does not know must be refused.

        The old version made the Mock's ``connect`` raise and asserted
        ``False``; it proved only that the ``except`` clause exists. This one
        offers a real, valid, correctly-formed key that simply is not
        authorized -- the case that actually happens.
        """
        authorized = generate_keypair(isolated_home / ".ssh", "id_ed25519")
        _authorize(ssh_server, f"{authorized}.pub")
        stranger = generate_keypair(isolated_home / ".ssh", "not_authorized")

        config = _config(ssh_server)

        assert (
            validate_ssh_key(
                ssh_server.host,
                "testuser",
                str(stranger),
                ssh_server.port,
                config=config,
            )
            is False
        )
        # And a host that is not listening at all is also False, not a crash.
        assert (
            validate_ssh_key(
                ssh_server.host,
                "testuser",
                str(authorized),
                _closed_port(),
                config=config,
            )
            is False
        )

    def test_detect_working_ssh_key(self, isolated_home, ssh_server):
        """The key that is found is the one that really authenticates.

        The old version patched ``detect_existing_ssh_key`` and asserted the
        alias forwarded to it -- a test of one line of delegation. Two real
        standard-named keys exist here and only one is authorized, so the
        answer can only be right if a real connection decided it.
        """
        _ = generate_keypair(isolated_home / ".ssh", "id_rsa")
        working = generate_keypair(isolated_home / ".ssh", "id_ed25519")
        _authorize(ssh_server, f"{working}.pub")

        found = detect_working_ssh_key(
            ssh_server.host, "testuser", ssh_server.port, config=_config(ssh_server)
        )

        assert found == str(working)

    def test_generate_ssh_key_pair(self, tmp_path):
        """Really generate a key pair, and check what landed on disk.

        The old version patched ``subprocess.run`` *and*
        ``clustrix.ssh_utils.generate_ssh_key``, then asserted the stub's
        return value came back -- so it never ran ``ssh-keygen`` and never
        looked at a file.
        """
        private_path, public_path = generate_ssh_key_pair(
            "test_key", key_type="ed25519", key_dir=tmp_path
        )

        assert private_path == str(tmp_path / "test_key")
        assert public_path == f"{private_path}.pub"
        assert Path(private_path).exists() and Path(public_path).exists()

        # The permissions matter: ssh refuses a world-readable private key.
        assert stat.S_IMODE(Path(private_path).stat().st_mode) == 0o600
        assert stat.S_IMODE(Path(public_path).stat().st_mode) == 0o644

        # Real key material: loadable, and the two halves are a real pair.
        loaded = paramiko.Ed25519Key.from_private_key_file(private_path)
        assert Path(public_path).read_text().split()[1] == loaded.get_base64()

    def test_deploy_ssh_key(self, isolated_home, ssh_server):
        """Deploy a real key over real SSH, then log in with it.

        The old version patched ``deploy_public_key`` and asserted the alias
        forwarded its arguments. Nothing was deployed and no host was touched.
        """
        private_key = generate_keypair(isolated_home / ".ssh", "id_ed25519")

        deployed = deploy_ssh_key(
            ssh_server.host,
            "testuser",
            SSH_PASSWORD,
            f"{private_key}.pub",
            ssh_server.port,
            config=_config(ssh_server),
        )

        assert deployed is True
        authorized = ssh_server.root_path / ".ssh" / "authorized_keys"
        assert Path(f"{private_key}.pub").read_text().split()[1] in (
            authorized.read_text()
        )
        # The deployment is only real if the key now works.
        assert validate_ssh_key(
            ssh_server.host,
            "testuser",
            str(private_key),
            ssh_server.port,
            config=_config(ssh_server),
        )

    def test_find_ssh_keys(self, isolated_home):
        """Real files, real permissions, real contents.

        The old version patched ``Path.home``, ``Path.exists``,
        ``Path.is_file``, ``Path.stat`` and ``builtins.open``, then asserted
        only ``isinstance(result, list)`` -- its own comment admitted it did
        not know what it expected. Every rule ``find_ssh_keys`` applies is
        checked here against a file that really breaks it.
        """
        ssh_dir = isolated_home / ".ssh"

        good = generate_keypair(ssh_dir, "id_ed25519")

        # Right name, right contents, but group/other-readable: rejected.
        loose = generate_keypair(ssh_dir, "id_rsa")
        os.chmod(loose, 0o644)

        # Right name and right permissions, but not a private key.
        (ssh_dir / "id_ecdsa").write_text("this is not a key\n")
        os.chmod(ssh_dir / "id_ecdsa", 0o600)

        # Right everything, but not a name find_ssh_keys looks for.
        unlisted = generate_keypair(ssh_dir, "id_something_else")

        # A key clustrix generated for itself, named the way setup_ssh_keys
        # really names one. Before #154 this was invisible to discovery, so
        # clustrix could not find its own key.
        generated = generate_keypair(ssh_dir, "id_ed25519_clustrix_testuser_alias")

        # Things that live in ~/.ssh and are emphatically not private keys.
        (ssh_dir / "config").write_text("Host example\n")
        (ssh_dir / "known_hosts").write_text("example ssh-ed25519 AAAA\n")
        os.chmod(ssh_dir / "config", 0o600)
        os.chmod(ssh_dir / "known_hosts", 0o600)

        found = find_ssh_keys()

        assert found == [str(good), str(generated)]
        assert str(loose) not in found
        assert str(unlisted) not in found
        # The public half of a key clustrix generated is not a private key.
        assert f"{generated}.pub" not in found
        assert str(ssh_dir / "config") not in found
        assert str(ssh_dir / "known_hosts") not in found


class TestSSHKeyErrorHandling:
    """Error paths, produced by real failures rather than by stubs."""

    def test_deployment_failure(self, isolated_home, ssh_server):
        """A wrong password really fails to deploy, and says so.

        The old version patched ``deploy_public_key`` to return ``False``.
        Here the server really rejects the credential.
        """
        config = _config(ssh_server)

        result = setup_ssh_keys(config, password="wrong-password")

        assert not result["success"]
        assert "Failed to deploy public key" in result["error"]
        # It got far enough to generate a key; it did not get in.
        assert Path(result["key_path"]).exists()
        assert not (ssh_server.root_path / ".ssh" / "authorized_keys").exists()

    def test_key_generation_failure(self, isolated_home, ssh_server):
        """``ssh-keygen`` really fails, and the failure is reported.

        The old version set ``mock_generate.side_effect =
        SSHKeyGenerationError(...)``: it raised the exception itself and then
        checked it was caught. Asking ``ssh-keygen`` for a key type it does
        not implement makes the real tool fail for a real reason.
        """
        config = _config(ssh_server)

        result = setup_ssh_keys(config, password=SSH_PASSWORD, key_type="rsa1024")

        assert not result["success"]
        assert "Failed to generate SSH key" in result["error"]
        assert not Path(result["key_path"]).exists()


def _closed_port() -> int:
    """A real port number with nothing listening on it."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
        probe.bind(("127.0.0.1", 0))
        return probe.getsockname()[1]
