"""Real tests for the Kubernetes backend's result handling (#119).

No mocks. The worker program the container runs is generated by
``build_worker_program`` and executed here with the real interpreter, so these
tests exercise the same code a pod would run. What cannot be exercised without
a cluster is the Kubernetes API itself -- and for that the tests assert the
error behaviour, which is the part that was wrong: a status that could not be
read was reported as "completed".
"""

import base64
import hashlib
import hmac
import os
import subprocess
import sys
from datetime import datetime, timedelta

import dill
import pytest

from clustrix.config import ClusterConfig
from clustrix.executor_connections import ConnectionManager
from clustrix.executor_kubernetes import (
    KubernetesJobManager,
    build_container_command,
    build_worker_program,
    decode_signed_result,
)
from clustrix.utils import serialize_function


def measure(scale):
    """Return an object with no literal repr.

    ``ast.literal_eval(repr(datetime(...)))`` raises, so under the old path
    this came back as the *string* "datetime.datetime(2026, 1, 6, 0, 0)" and
    the caller had no way to tell that from a real answer.
    """
    return datetime(2026, 1, 1) + timedelta(days=scale)


def explode(message):
    raise ValueError(message)


def _run_worker(func, args, kwargs, key):
    """Run the real generated worker program and return (proc, program)."""
    func_data = serialize_function(func, args, kwargs)
    import cloudpickle

    b64 = base64.b64encode(cloudpickle.dumps(func_data)).decode("utf-8")
    program = build_worker_program(b64)

    env = dict(os.environ)
    env["CLUSTRIX_RESULT_KEY"] = key
    proc = subprocess.run(
        [sys.executable, "-c", program],
        capture_output=True,
        text=True,
        env=env,
        timeout=120,
    )
    return proc, program


def test_worker_returns_a_real_object_not_its_repr():
    key = "0" * 64
    proc, _ = _run_worker(measure, (5,), {}, key)

    assert proc.returncode == 0, proc.stderr
    result = decode_signed_result(proc.stdout, key)
    assert result == datetime(2026, 1, 6)
    assert isinstance(result, datetime)
    # The old marker is gone entirely, so nothing can fall back to a repr.
    assert "CLUSTRIX_RESULT:" not in proc.stdout


def test_worker_failure_is_never_decoded_as_a_result():
    key = "1" * 64
    proc, _ = _run_worker(explode, ("boom",), {}, key)

    assert proc.returncode == 1
    assert "CLUSTRIX_ERROR:boom" in proc.stdout
    assert "CLUSTRIX_TRACEBACK:" in proc.stdout

    with pytest.raises(RuntimeError, match="no clustrix result"):
        decode_signed_result(proc.stdout, key)


def test_worker_refuses_to_run_without_a_signing_key():
    func_data = serialize_function(measure, (2,), {})
    import cloudpickle

    b64 = base64.b64encode(cloudpickle.dumps(func_data)).decode("utf-8")
    env = dict(os.environ)
    env.pop("CLUSTRIX_RESULT_KEY", None)

    proc = subprocess.run(
        [sys.executable, "-c", build_worker_program(b64)],
        capture_output=True,
        text=True,
        env=env,
        timeout=120,
    )

    assert proc.returncode == 1
    assert "CLUSTRIX_RESULT_KEY is not set" in proc.stdout


def test_decode_rejects_a_tampered_payload():
    key = "2" * 64
    forged = dill.dumps(datetime(1999, 9, 9), protocol=4)
    logs = (
        "CLUSTRIX_RESULT_B64:"
        + base64.b64encode(forged).decode()
        + "\nCLUSTRIX_RESULT_HMAC:"
        + hmac.new(b"wrong-key", forged, hashlib.sha256).hexdigest()
        + "\n"
    )

    with pytest.raises(RuntimeError, match="integrity check"):
        decode_signed_result(logs, key)


def test_decode_rejects_an_unsigned_result():
    payload = dill.dumps(datetime(2000, 1, 1), protocol=4)
    logs = "CLUSTRIX_RESULT_B64:" + base64.b64encode(payload).decode() + "\n"

    with pytest.raises(RuntimeError, match="no signature"):
        decode_signed_result(logs, result_key="3" * 64)


def test_decode_rejects_the_old_repr_style_marker():
    """The pre-fix worker printed `CLUSTRIX_RESULT:<repr>`; it is not a result."""
    with pytest.raises(RuntimeError, match="no clustrix result"):
        decode_signed_result("CLUSTRIX_RESULT:42\n", result_key="4" * 64)


def test_decode_never_returns_the_raw_log():
    logs = "some unrelated pod chatter\nmore chatter\n"
    with pytest.raises(RuntimeError):
        decode_signed_result(logs, result_key="5" * 64)


def test_container_command_refuses_shell_metacharacters():
    with pytest.raises(ValueError, match="shell would"):
        build_container_command('print("hi")')
    with pytest.raises(ValueError, match="shell would"):
        build_container_command("print('$HOME')")


def test_generated_worker_program_is_shell_safe():
    func_data = serialize_function(measure, (1,), {})
    import cloudpickle

    b64 = base64.b64encode(cloudpickle.dumps(func_data)).decode("utf-8")
    command = build_container_command(build_worker_program(b64))
    assert command.count('"') == 2  # only the two wrapping python -c quotes


def test_unreadable_job_status_is_an_error_not_completed():
    """A status that cannot be read used to be reported as success.

    There is no cluster here, so the API call genuinely fails -- which is
    precisely the situation that used to return "completed" for any job the
    manager happened to be tracking.
    """
    config = ClusterConfig(cluster_type="kubernetes", k8s_namespace="default")
    manager = KubernetesJobManager(config, ConnectionManager(config))
    manager.active_jobs["clustrix-job-1-2"] = {
        "status": "submitted",
        "k8s_job": True,
        "result_key": "6" * 64,
    }

    with pytest.raises(Exception) as excinfo:
        status = manager.check_k8s_job_status("clustrix-job-1-2")
        pytest.fail(f"expected a failure, got status {status!r}")

    assert "completed" not in str(excinfo.value)


def test_result_collection_without_a_cluster_is_an_error():
    config = ClusterConfig(cluster_type="kubernetes", k8s_namespace="default")
    manager = KubernetesJobManager(config, ConnectionManager(config))
    manager.active_jobs["clustrix-job-3-4"] = {
        "status": "submitted",
        "k8s_job": True,
        "result_key": "7" * 64,
    }

    with pytest.raises(Exception):
        manager.get_k8s_result("clustrix-job-3-4")
