name: Coverage Badge

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  coverage-badge:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,test]"
        pip install coverage-badge

    - name: Run tests with coverage
      run: |
        pytest tests/ -v --cov=clustrix --cov-report=xml --cov-report=term

    - name: Generate coverage badge
      run: |
        coverage-badge -o coverage.svg -f

    - name: Verify badge created
      run: |
        ls -la coverage.svg
        cat coverage.svg | head -5

    - name: Commit badge
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add coverage.svg
        git diff --staged --quiet || git commit -m "Update coverage badge" || echo "No changes to commit"

    - name: Push badge
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        force: false